export const LOAD_DATA = "LOAD_DATA";
export const LOAD_DATA_SUCCESS = "LOAD_DATA_SUCCESS";
export const GET_FORM_DATA = "GET_FORM_DATA";
export const ADD_HOTEL_TO_FAVORITES = "ADD_HOTEL_TO_FAVORITES";
export const DEL_HOTEL_TO_FAVORITES = "DEL_HOTEL_TO_FAVORITES";